import { api } from '../api/client'

/**
 * Digital signature for generated reports.
 *
 * Flow: hash the report's DATA (the rows/facts, before rendering) with
 * SHA-256 in the browser, send only the hash to the server, get back a
 * verification ID + HMAC signature (secret key never leaves the server),
 * and print both on the report. Anyone can later enter the verification ID
 * on the Reports page — a document whose ID is unknown, or whose stored
 * hash/signature don't match, was NOT generated by this system.
 */
export interface ReportSignature {
  verifyId: string
  signature: string
  signedAt: string
}

export async function sha256Hex(data: string): Promise<string> {
  const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(data))
  return [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, '0')).join('')
}

/**
 * Sign a report's content. Returns null when the server is unreachable —
 * the report still downloads, marked "unsigned", rather than failing.
 */
export async function signReportContent(
  caseId: string,
  reportType: string,
  content: unknown,
): Promise<ReportSignature | null> {
  try {
    const hash = await sha256Hex(JSON.stringify(content))
    const out = await api.signReport(caseId, reportType, hash)
    return { verifyId: out.verify_id, signature: out.signature, signedAt: out.signed_at }
  } catch {
    return null
  }
}

/** One-line signature block for PDF footers / Excel summary rows. */
export function signatureLine(sig: ReportSignature | null): string {
  if (!sig) return 'UNSIGNED — generated while the signing service was unreachable'
  return (
    `Digitally signed by TraceNet — Verification ID: ${sig.verifyId} — ` +
    `Signature: ${sig.signature.slice(0, 16)}… — verify on the Reports page`
  )
}
